version: '3'
services:
  rails:
    image: h3poteto/rails:2.4.2
    environment:
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: /bin/bash

