# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bedf051b487edee602d327f29653ed9645ae9f56fc8ab5ef138a7aa1a42d96ebadf24e8e7c696e5b6331d73216f7e530af5e34af2adebaf009070607a048c201

test:
  secret_key_base: a2bf65713913069000e9517d22dc5e7fba571dcc666a6f93577fbd237caf84f3e1b797c89b8db0f1ed0b3f315b2e09cf2cd81ac2b2d261a6615d8d0326b0a8e1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
